# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # - name: Install Python 2.7.10
      #   shell: cmd
      #   run: |
      #     choco install wget --no-progress
      #     wget -nv "https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi"
      #     start /wait msiexec.exe /passive /i python-2.7.18.amd64.msi /norestart /L*V "python_install.log" ADDLOCAL=ALL ALLUSERS=1 TARGETDIR=c:\python27
      #     type "python_install.log"
      # - run: python2 -V
      - name: Use community action
        uses: MatteoH2O1999/setup-python@v2
        with:
          python-version: '2.7.10'
          allow-build: 'allow'
      - run: |
          python -V
          
          
