name: Post welcome comment
on:
  workflow_dispatch:
jobs:
  build:
    name: Test jfrog cli
    runs-on: ubuntu-latest
    steps:
      - run: |
          Test-NetConnection artifactory.fis.dev -Pot 443
      - uses: jfrog/setup-jfrog-cli@v3.1.0
      - run: |
          jf rt ping --url=https://artifactory.fis.dev

